version: '3'
services:
  selenium_driver:
    image: selenium/standalone-chrome:114.0
    ports:
      - target: 4444
        published: 4444
        protocol: tcp
        mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://selenium_driver:4444/wd/hub/status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - test_network

networks:
  test_network:
    driver: bridge
